[project]
name = "grasppanda"
version = "0.40.0"
description = "Modular visual grasping toolbox with a shared runtime and experiment UI"
requires-python = ">=3.11,<3.12"
dependencies = [
  "flash-attn==2.7.3",
  "colorhash",
  "xformers==0.0.28.post3",
  "torch==2.5.1",
  "torchvision==0.20.1",
  "numpy==1.23.5",
  "scipy==1.10.1",
  "setuptools==74.1.3",
  "wheel==0.48.0",
  "ninja",
  "Cython<3",
  "open3d==0.18.0",
  "numba==0.60.0",
  "matplotlib<3.9",
  "pandas<2.3",
  "scikit-learn<1.6",
  "opencv-python<4.12",
  "pillow",
  "tqdm",
  "tensorboard",
  "tensorboardX",
  "transforms3d",
  "trimesh",
  "h5py",
  "pyyaml",
  "easydict",
  "einops",
  "timm",
  "fvcore",
  "iopath",
  "plyfile",
  "torchsummary",
  "scikit-image",
  "cvxopt",
  "autolab-core",
  "autolab-perception",
  "pywavefront",
  "dill",
  "hydra-core",
  "spconv-cu118==2.3.8",
  "addict",
  "dgl==1.1.3",
  "torch-geometric==2.6.1",
  "gdown",
  "roma>=1.6.1",
  "lightning>=2.6.5",
  "webdataset>=1.0.2",
  "kornia>=0.8.2",
  "colour>=0.1.5",
  "segmentation-models-pytorch>=0.5.0",
  "shortuuid>=1.0.13",
  "zstandard>=0.25.0",
  "pycocotools>=2.0.11",
  "spatialmath-python>=1.1.17",
  "gradio>=6,<7",
  "pybind11>=3.1.0",
  "rotary-embedding-torch==0.3.5",
  "siren-pytorch>=0.1.7",
  "pymcubes>=0.1.6",
  "ocnn>=2.3.3",
  "wandb>=0.29.0",
  "datasettemplate",
  "launchertemplate",
  "ipython>=9.17.1",
  "ipywidgets>=8.1.9",
  "ultralytics==8.0.120",
  "clip",
  "shapely>=2.1.2",
  "alphashape>=1.3.1",
  "zarr<3",
  "cupoch==0.2.11.0",
  "thop>=0.1.1.post2209072238",
  "colorama>=0.4.6",
  "pytorch-kinematics>=0.10.0",
  "mplib==0.1.1",
  "sapien==2.2.2",
  "mesh-to-sdf==0.0.15",
  "pytorch-ignite>=0.5.5",
  "accelerate==1.10.1",
  "transformers==5.0.0",
  "deprecated",
  "timeout-decorator",
  "robo-orchard-core",
  "fpsample==0.3.3",
  "tensordict==0.6.2",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu118" }
torchvision = { index = "pytorch-cu118" }
datasettemplate = { git = "https://github.com/Nx1021/DatasetTemplate", rev = "9543930258cf4ba98e543ad6b654d2088049a329" }
launchertemplate = { git = "https://github.com/Nx1021/LauncherTemplate", rev = "eb8d0df9a0fa1d0b66934e013df6fe64030d8e33" }

xformers = { index = "pytorch-cu118" }
clip = { git = "https://github.com/openai/CLIP", rev = "d05afc436d78f1c48dc0dbf8e5980a9d471f35f6" }
dgl = { url = "https://data.dgl.ai/wheels/cu118/dgl-1.1.3%2Bcu118-cp311-cp311-manylinux1_x86_64.whl" }

robo-orchard-core = { git = "https://github.com/HorizonRobotics/RoboOrchardCore", rev = "f760a53f851c00dbde55a081dd2976f031911ec1" }

flash-attn = { url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.3/flash_attn-2.7.3%2Bcu11torch2.5cxx11abiFALSE-cp311-cp311-linux_x86_64.whl" }
